version: '3'

services:
  web:
    image: joerx/nginx-fpm
    ports:
      - '8080:80'
    links:
      - app # fpm on port 9000
    environment:
      FPM_HOST: app
      FPM_PORT: 9000
    volumes:
      - pub-files:/var/www/html/public
  app:
    build: .
    volumes:
      - pub-files:/var/www/html/public

volumes:
  pub-files:
