version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    ports:
      - '8080:80'
    links:
      - app # fpm on port 9000
  app:
    build: .
    volumes:
      - .:/var/www/html
